name: Deploy Bucket

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install test dependencies
        run: |
          pip install -r tests/requirements.txt
      - name: Run tests
        run: python -m pytest